# Generated by Django 5.2.17 on 2026-09-27 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_seed_reference_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE_IN', 'Purchase Received'), ('SALE_OUT', 'Sold'), ('ADJUSTMENT_IN', 'Stock Adjustment (Add)'), ('ADJUSTMENT_OUT', 'Stock Adjustment (Remove)'), ('DAMAGED', 'Damaged Stock'), ('EXPIRED', 'Expired Stock'), ('PURCHASE_REVERSED', 'Purchase Cancelled')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Always positive; direction comes from movement_type.', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Batch quantity after this movement.', max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='e.g. PUR-12, SALE-45', max_length=100)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.batch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_movement_quantity_gt_0')],
            },
        ),
    ]
