# Generated by Django 5.2.17 on 2026-10-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE_IN', 'Purchase Received'), ('SALE_OUT', 'Sold'), ('ADJUSTMENT_IN', 'Stock Adjustment (Add)'), ('ADJUSTMENT_OUT', 'Stock Adjustment (Remove)'), ('DAMAGED', 'Damaged Stock'), ('EXPIRED', 'Expired Stock'), ('PURCHASE_REVERSED', 'Purchase Cancelled'), ('SALE_REVERSED', 'Sale Cancelled'), ('RETURN_IN', 'Customer Return')], max_length=20),
        ),
    ]
