-- =====================================================================
-- Pesticide Club Shop: 001_init.sql
-- SQLite schema. Run once on an empty database.
--
-- Conventions
--   * Primary keys are UUIDs stored as TEXT (generated by the app).
--   * Money is INTEGER paisa. Prices are per pack.
--   * Quantities are INTEGER in the base unit (ml, g or piece).
--       line_total = ROUND(qty * unit_price / pack_size) - line_discount + tax_amount
--       invoice.subtotal = SUM(line_total - tax_amount), invoice.total = subtotal + tax_total
--   * Timestamps are UTC ISO text.
--   * Stock and balances are never stored. They are sums over
--     stock_movements and ledger_entries (see the v_ views).
--   * Ledger sign: plus means the party owes more (customers) or we owe more (suppliers).
--   * Editable and header tables carry updated_at, deleted_at and version.
--     The database maintains updated_at and version itself. Never set them in the app.
--   * Append-only and line tables are never edited or deleted. Fix mistakes with a
--     reversing row. Other tables are never hard-deleted. Set deleted_at instead.
--   * Every insert or update on a syncable table writes a row to change_log.
--
-- Run on EVERY connection (foreign_keys is not stored in the file):
--     PRAGMA foreign_keys = ON;
-- =====================================================================

PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;


-- ---------- setup ----------
CREATE TABLE shops (
    id         TEXT PRIMARY KEY,
    name       TEXT NOT NULL,
    phone      TEXT,
    address    TEXT,
    currency   TEXT NOT NULL DEFAULT 'PKR',
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    deleted_at TEXT,
    version    INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE branches (
    id         TEXT PRIMARY KEY,
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    name       TEXT NOT NULL,
    code       TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    deleted_at TEXT,
    version    INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE devices (
    id          TEXT PRIMARY KEY,
    branch_id   TEXT NOT NULL REFERENCES branches(id),
    name        TEXT NOT NULL,
    device_code TEXT NOT NULL UNIQUE,
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    deleted_at  TEXT,
    version     INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE users (
    id            TEXT PRIMARY KEY,
    name          TEXT NOT NULL,
    username      TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role          TEXT NOT NULL CHECK (role IN ('owner','staff')),
    is_active     INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    branch_id  TEXT NOT NULL REFERENCES branches(id),
    device_id  TEXT NOT NULL REFERENCES devices(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    deleted_at TEXT,
    version    INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE settings (
    id    TEXT PRIMARY KEY,
    "key" TEXT NOT NULL UNIQUE,
    value TEXT,
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    branch_id  TEXT NOT NULL REFERENCES branches(id),
    device_id  TEXT NOT NULL REFERENCES devices(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    deleted_at TEXT,
    version    INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE number_sequences (
    id            TEXT PRIMARY KEY,
    device_id     TEXT NOT NULL REFERENCES devices(id),
    sequence_name TEXT NOT NULL,
    prefix        TEXT NOT NULL,
    last_number   INTEGER NOT NULL DEFAULT 0 CHECK (last_number >= 0),
    updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    UNIQUE (device_id, sequence_name)
);

-- ---------- catalog ----------
CREATE TABLE categories (
    id      TEXT PRIMARY KEY,
    name_en TEXT,
    name_ur TEXT,
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    branch_id  TEXT NOT NULL REFERENCES branches(id),
    device_id  TEXT NOT NULL REFERENCES devices(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    deleted_at TEXT,
    version    INTEGER NOT NULL DEFAULT 1,
    CHECK (name_en IS NOT NULL OR name_ur IS NOT NULL)
);

CREATE TABLE brands (
    id      TEXT PRIMARY KEY,
    name_en TEXT,
    name_ur TEXT,
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    branch_id  TEXT NOT NULL REFERENCES branches(id),
    device_id  TEXT NOT NULL REFERENCES devices(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    deleted_at TEXT,
    version    INTEGER NOT NULL DEFAULT 1,
    CHECK (name_en IS NOT NULL OR name_ur IS NOT NULL)
);

CREATE TABLE suppliers (
    id      TEXT PRIMARY KEY,
    name_en TEXT,
    name_ur TEXT,
    phone   TEXT,
    address TEXT,
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    branch_id  TEXT NOT NULL REFERENCES branches(id),
    device_id  TEXT NOT NULL REFERENCES devices(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    deleted_at TEXT,
    version    INTEGER NOT NULL DEFAULT 1,
    CHECK (name_en IS NOT NULL OR name_ur IS NOT NULL)
);

CREATE TABLE customers (
    id                 TEXT PRIMARY KEY,
    name_en            TEXT,
    name_ur            TEXT,
    phone              TEXT,
    village            TEXT,
    credit_limit       INTEGER NOT NULL DEFAULT 0 CHECK (credit_limit >= 0),
    default_price_type TEXT NOT NULL DEFAULT 'retail' CHECK (default_price_type IN ('retail','wholesale')),
    notes              TEXT,
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    branch_id  TEXT NOT NULL REFERENCES branches(id),
    device_id  TEXT NOT NULL REFERENCES devices(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    deleted_at TEXT,
    version    INTEGER NOT NULL DEFAULT 1,
    CHECK (name_en IS NOT NULL OR name_ur IS NOT NULL)
);

CREATE TABLE products (
    id              TEXT PRIMARY KEY,
    category_id     TEXT REFERENCES categories(id),
    brand_id        TEXT REFERENCES brands(id),
    name_en         TEXT,
    name_ur         TEXT,
    sku             TEXT UNIQUE,
    barcode         TEXT UNIQUE,
    base_unit       TEXT NOT NULL CHECK (base_unit IN ('ml','g','piece')),
    pack_size       INTEGER NOT NULL CHECK (pack_size > 0),
    allow_loose     INTEGER NOT NULL DEFAULT 0 CHECK (allow_loose IN (0,1)),
    retail_price    INTEGER NOT NULL CHECK (retail_price >= 0),
    wholesale_price INTEGER NOT NULL CHECK (wholesale_price >= 0),
    tax_rate_bp     INTEGER NOT NULL DEFAULT 0 CHECK (tax_rate_bp BETWEEN 0 AND 10000),
    min_stock       INTEGER NOT NULL DEFAULT 0 CHECK (min_stock >= 0),
    is_active       INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    branch_id  TEXT NOT NULL REFERENCES branches(id),
    device_id  TEXT NOT NULL REFERENCES devices(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    deleted_at TEXT,
    version    INTEGER NOT NULL DEFAULT 1,
    CHECK (name_en IS NOT NULL OR name_ur IS NOT NULL)
);

CREATE TABLE batches (
    id          TEXT PRIMARY KEY,
    product_id  TEXT NOT NULL REFERENCES products(id),
    supplier_id TEXT REFERENCES suppliers(id),
    batch_no    TEXT NOT NULL,
    expiry_date TEXT NOT NULL,
    cost_price  INTEGER NOT NULL CHECK (cost_price >= 0),
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    branch_id  TEXT NOT NULL REFERENCES branches(id),
    device_id  TEXT NOT NULL REFERENCES devices(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    deleted_at TEXT,
    version    INTEGER NOT NULL DEFAULT 1,
    UNIQUE (product_id, batch_no)
);

-- ---------- purchasing ----------
CREATE TABLE purchases (
    id                  TEXT PRIMARY KEY,
    supplier_id         TEXT NOT NULL REFERENCES suppliers(id),
    supplier_invoice_no TEXT,
    purchase_date       TEXT NOT NULL DEFAULT (date('now')),
    discount            INTEGER NOT NULL DEFAULT 0 CHECK (discount >= 0),
    total               INTEGER NOT NULL CHECK (total >= 0),
    paid_amount         INTEGER NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    branch_id  TEXT NOT NULL REFERENCES branches(id),
    device_id  TEXT NOT NULL REFERENCES devices(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    deleted_at TEXT,
    version    INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE purchase_items (
    id          TEXT PRIMARY KEY,
    purchase_id TEXT NOT NULL REFERENCES purchases(id),
    batch_id    TEXT NOT NULL REFERENCES batches(id),
    qty         INTEGER NOT NULL CHECK (qty > 0),
    cost_price  INTEGER NOT NULL CHECK (cost_price >= 0),
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    branch_id  TEXT NOT NULL REFERENCES branches(id),
    device_id  TEXT NOT NULL REFERENCES devices(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    version    INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE purchase_returns (
    id          TEXT PRIMARY KEY,
    supplier_id TEXT NOT NULL REFERENCES suppliers(id),
    purchase_id TEXT REFERENCES purchases(id),
    return_date TEXT NOT NULL DEFAULT (date('now')),
    reason      TEXT,
    total       INTEGER NOT NULL CHECK (total >= 0),
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    branch_id  TEXT NOT NULL REFERENCES branches(id),
    device_id  TEXT NOT NULL REFERENCES devices(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    deleted_at TEXT,
    version    INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE purchase_return_items (
    id                 TEXT PRIMARY KEY,
    purchase_return_id TEXT NOT NULL REFERENCES purchase_returns(id),
    batch_id           TEXT NOT NULL REFERENCES batches(id),
    qty                INTEGER NOT NULL CHECK (qty > 0),
    cost_price         INTEGER NOT NULL CHECK (cost_price >= 0),
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    branch_id  TEXT NOT NULL REFERENCES branches(id),
    device_id  TEXT NOT NULL REFERENCES devices(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    version    INTEGER NOT NULL DEFAULT 1
);

-- ---------- sales ----------
CREATE TABLE invoices (
    id           TEXT PRIMARY KEY,
    invoice_no   TEXT NOT NULL UNIQUE,
    customer_id  TEXT REFERENCES customers(id),
    created_by   TEXT NOT NULL REFERENCES users(id),
    invoice_date TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    due_date     TEXT,
    price_type   TEXT NOT NULL DEFAULT 'retail' CHECK (price_type IN ('retail','wholesale')),
    subtotal     INTEGER NOT NULL CHECK (subtotal >= 0),
    tax_total    INTEGER NOT NULL DEFAULT 0 CHECK (tax_total >= 0),
    total        INTEGER NOT NULL CHECK (total >= 0),
    paid_amount  INTEGER NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),
    status       TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','voided')),
    void_reason  TEXT,
    voided_by    TEXT REFERENCES users(id),
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    branch_id  TEXT NOT NULL REFERENCES branches(id),
    device_id  TEXT NOT NULL REFERENCES devices(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    deleted_at TEXT,
    version    INTEGER NOT NULL DEFAULT 1,
    CHECK (total = subtotal + tax_total),
    CHECK (paid_amount <= total),
    CHECK (customer_id IS NOT NULL OR paid_amount = total),
    CHECK (status = 'active' OR (void_reason IS NOT NULL AND voided_by IS NOT NULL))
);

CREATE TABLE invoice_items (
    id            TEXT PRIMARY KEY,
    invoice_id    TEXT NOT NULL REFERENCES invoices(id),
    product_id    TEXT NOT NULL REFERENCES products(id),
    batch_id      TEXT NOT NULL REFERENCES batches(id),
    qty           INTEGER NOT NULL CHECK (qty > 0),
    unit_price    INTEGER NOT NULL CHECK (unit_price >= 0),
    cost_price    INTEGER NOT NULL CHECK (cost_price >= 0),
    line_discount INTEGER NOT NULL DEFAULT 0 CHECK (line_discount >= 0),
    tax_rate_bp   INTEGER NOT NULL DEFAULT 0 CHECK (tax_rate_bp BETWEEN 0 AND 10000),
    tax_amount    INTEGER NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    line_total    INTEGER NOT NULL CHECK (line_total >= 0),
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    branch_id  TEXT NOT NULL REFERENCES branches(id),
    device_id  TEXT NOT NULL REFERENCES devices(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    version    INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE sales_returns (
    id            TEXT PRIMARY KEY,
    return_no     TEXT NOT NULL UNIQUE,
    invoice_id    TEXT NOT NULL REFERENCES invoices(id),
    approved_by   TEXT NOT NULL REFERENCES users(id),
    return_date   TEXT NOT NULL DEFAULT (date('now')),
    reason        TEXT,
    refund_method TEXT NOT NULL CHECK (refund_method IN ('cash','khata_credit')),
    total         INTEGER NOT NULL CHECK (total >= 0),
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    branch_id  TEXT NOT NULL REFERENCES branches(id),
    device_id  TEXT NOT NULL REFERENCES devices(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    deleted_at TEXT,
    version    INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE sales_return_items (
    id              TEXT PRIMARY KEY,
    sales_return_id TEXT NOT NULL REFERENCES sales_returns(id),
    invoice_item_id TEXT NOT NULL REFERENCES invoice_items(id),
    qty             INTEGER NOT NULL CHECK (qty > 0),
    refund_amount   INTEGER NOT NULL CHECK (refund_amount >= 0),
    condition       TEXT NOT NULL CHECK (condition IN ('resellable','damaged','expired')),
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    branch_id  TEXT NOT NULL REFERENCES branches(id),
    device_id  TEXT NOT NULL REFERENCES devices(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    version    INTEGER NOT NULL DEFAULT 1
);

-- ---------- stock and money ----------
CREATE TABLE stock_movements (
    id            TEXT PRIMARY KEY,
    batch_id      TEXT NOT NULL REFERENCES batches(id),
    qty_delta     INTEGER NOT NULL CHECK (qty_delta <> 0),
    movement_type TEXT NOT NULL CHECK (movement_type IN
        ('opening','purchase','sale','sale_return','purchase_return','void','adjustment','damage','expired')),
    ref_type      TEXT,
    ref_id        TEXT,
    created_by    TEXT REFERENCES users(id),
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    branch_id  TEXT NOT NULL REFERENCES branches(id),
    device_id  TEXT NOT NULL REFERENCES devices(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    version    INTEGER NOT NULL DEFAULT 1,
    CHECK (
        (movement_type IN ('opening','purchase','sale_return','void') AND qty_delta > 0) OR
        (movement_type IN ('sale','purchase_return','damage','expired') AND qty_delta < 0) OR
        movement_type = 'adjustment'
    )
);

CREATE TABLE payments (
    id          TEXT PRIMARY KEY,
    party_type  TEXT NOT NULL CHECK (party_type IN ('customer','supplier')),
    party_id    TEXT NOT NULL,
    method      TEXT NOT NULL CHECK (method IN ('cash','bank','easypaisa','jazzcash')),
    reference_no TEXT,
    amount      INTEGER NOT NULL CHECK (amount > 0),
    direction   TEXT NOT NULL CHECK (direction IN ('in','out')),
    paid_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    created_by  TEXT REFERENCES users(id),
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    branch_id  TEXT NOT NULL REFERENCES branches(id),
    device_id  TEXT NOT NULL REFERENCES devices(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    version    INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE ledger_entries (
    id           TEXT PRIMARY KEY,
    party_type   TEXT NOT NULL CHECK (party_type IN ('customer','supplier')),
    party_id     TEXT NOT NULL,
    entry_type   TEXT NOT NULL CHECK (entry_type IN
        ('opening','invoice','payment','return','adjustment','purchase','purchase_return')),
    amount_delta INTEGER NOT NULL CHECK (amount_delta <> 0),
    ref_type     TEXT,
    ref_id       TEXT,
    entry_date   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    created_by   TEXT REFERENCES users(id),
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    branch_id  TEXT NOT NULL REFERENCES branches(id),
    device_id  TEXT NOT NULL REFERENCES devices(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    version    INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE expenses (
    id           TEXT PRIMARY KEY,
    expense_date TEXT NOT NULL DEFAULT (date('now')),
    category     TEXT,
    description  TEXT,
    amount       INTEGER NOT NULL CHECK (amount > 0),
    method       TEXT CHECK (method IN ('cash','bank','easypaisa','jazzcash')),
    created_by   TEXT REFERENCES users(id),
    shop_id    TEXT NOT NULL REFERENCES shops(id),
    branch_id  TEXT NOT NULL REFERENCES branches(id),
    device_id  TEXT NOT NULL REFERENCES devices(id),
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    deleted_at TEXT,
    version    INTEGER NOT NULL DEFAULT 1
);

-- ---------- system logs ----------
CREATE TABLE audit_log (
    id         TEXT PRIMARY KEY,
    user_id    TEXT REFERENCES users(id),
    action     TEXT NOT NULL,
    table_name TEXT,
    row_id     TEXT,
    details    TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE change_log (
    id         TEXT PRIMARY KEY,
    table_name TEXT NOT NULL,
    row_id     TEXT NOT NULL,
    operation  TEXT NOT NULL CHECK (operation IN ('insert','update','delete')),
    payload    TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    synced_at  TEXT
);

CREATE TABLE backup_log (
    id          TEXT PRIMARY KEY,
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    destination TEXT NOT NULL,
    file_name   TEXT,
    size_bytes  INTEGER,
    checksum    TEXT,
    status      TEXT NOT NULL CHECK (status IN ('ok','failed')),
    error       TEXT
);

CREATE TABLE schema_version (
    version     INTEGER PRIMARY KEY,
    applied_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    description TEXT
);

-- ---------- indexes ----------
CREATE INDEX idx_products_name_en     ON products(name_en);
CREATE INDEX idx_products_name_ur     ON products(name_ur);
CREATE INDEX idx_batches_product_exp  ON batches(product_id, expiry_date);
CREATE INDEX idx_customers_name_en    ON customers(name_en);
CREATE INDEX idx_customers_name_ur    ON customers(name_ur);
CREATE INDEX idx_customers_phone      ON customers(phone);
CREATE INDEX idx_stock_batch           ON stock_movements(batch_id);
CREATE INDEX idx_ledger_party          ON ledger_entries(party_type, party_id, entry_date);
CREATE INDEX idx_payments_party        ON payments(party_type, party_id, paid_at);
CREATE INDEX idx_invoices_date         ON invoices(invoice_date);
CREATE INDEX idx_invoices_customer     ON invoices(customer_id);
CREATE INDEX idx_invoice_items_invoice ON invoice_items(invoice_id);
CREATE INDEX idx_invoice_items_batch   ON invoice_items(batch_id);
CREATE INDEX idx_invoice_items_product ON invoice_items(product_id);
CREATE INDEX idx_sales_returns_invoice ON sales_returns(invoice_id);
CREATE INDEX idx_sri_invoice_item      ON sales_return_items(invoice_item_id);
CREATE INDEX idx_purchase_items_purch  ON purchase_items(purchase_id);
CREATE INDEX idx_change_log_unsynced   ON change_log(created_at) WHERE synced_at IS NULL;

-- ---------- business rules enforced by the database ----------

-- Stock can never go below zero in a batch.
CREATE TRIGGER trg_stock_no_negative BEFORE INSERT ON stock_movements
WHEN NEW.qty_delta < 0
BEGIN
    SELECT RAISE(ABORT, 'insufficient stock in batch')
    WHERE (SELECT COALESCE(SUM(qty_delta), 0) FROM stock_movements WHERE batch_id = NEW.batch_id) + NEW.qty_delta < 0;
END;

-- Expired batches cannot be sold.
CREATE TRIGGER trg_stock_no_expired_sale BEFORE INSERT ON stock_movements
WHEN NEW.movement_type = 'sale'
BEGIN
    SELECT RAISE(ABORT, 'batch is expired')
    WHERE (SELECT expiry_date FROM batches WHERE id = NEW.batch_id) < date('now');
END;

-- Invoice lines: batch must belong to the product, packs only unless loose is allowed, invoice must be active.
CREATE TRIGGER trg_ii_batch_matches_product BEFORE INSERT ON invoice_items
BEGIN
    SELECT RAISE(ABORT, 'batch does not belong to product')
    WHERE NOT EXISTS (SELECT 1 FROM batches WHERE id = NEW.batch_id AND product_id = NEW.product_id);
END;

CREATE TRIGGER trg_ii_whole_packs BEFORE INSERT ON invoice_items
BEGIN
    SELECT RAISE(ABORT, 'product is sold in whole packs only')
    WHERE (SELECT allow_loose FROM products WHERE id = NEW.product_id) = 0
      AND NEW.qty % (SELECT pack_size FROM products WHERE id = NEW.product_id) <> 0;
END;

CREATE TRIGGER trg_ii_invoice_active BEFORE INSERT ON invoice_items
BEGIN
    SELECT RAISE(ABORT, 'invoice is voided')
    WHERE (SELECT status FROM invoices WHERE id = NEW.invoice_id) <> 'active';
END;

-- Returns: only against an active invoice, only items on that invoice, never more than was sold.
CREATE TRIGGER trg_sr_invoice_active BEFORE INSERT ON sales_returns
BEGIN
    SELECT RAISE(ABORT, 'cannot return against a voided invoice')
    WHERE (SELECT status FROM invoices WHERE id = NEW.invoice_id) <> 'active';
END;

CREATE TRIGGER trg_sri_item_on_invoice BEFORE INSERT ON sales_return_items
BEGIN
    SELECT RAISE(ABORT, 'item is not on the invoice being returned')
    WHERE NOT EXISTS (
        SELECT 1 FROM invoice_items ii JOIN sales_returns r ON r.invoice_id = ii.invoice_id
        WHERE ii.id = NEW.invoice_item_id AND r.id = NEW.sales_return_id);
END;

CREATE TRIGGER trg_sri_no_over_return BEFORE INSERT ON sales_return_items
BEGIN
    SELECT RAISE(ABORT, 'return exceeds quantity sold')
    WHERE COALESCE((SELECT SUM(qty) FROM sales_return_items WHERE invoice_item_id = NEW.invoice_item_id), 0) + NEW.qty
          > (SELECT qty FROM invoice_items WHERE id = NEW.invoice_item_id);
END;

-- Payments and ledger rows must point at a real customer or supplier.
CREATE TRIGGER trg_payments_party BEFORE INSERT ON payments
BEGIN
    SELECT RAISE(ABORT, 'unknown party')
    WHERE NOT EXISTS (SELECT 1 FROM customers WHERE id = NEW.party_id AND NEW.party_type = 'customer')
      AND NOT EXISTS (SELECT 1 FROM suppliers WHERE id = NEW.party_id AND NEW.party_type = 'supplier');
END;

CREATE TRIGGER trg_ledger_party BEFORE INSERT ON ledger_entries
BEGIN
    SELECT RAISE(ABORT, 'unknown party')
    WHERE NOT EXISTS (SELECT 1 FROM customers WHERE id = NEW.party_id AND NEW.party_type = 'customer')
      AND NOT EXISTS (SELECT 1 FROM suppliers WHERE id = NEW.party_id AND NEW.party_type = 'supplier');
END;

-- change_log rows are immutable except synced_at, and unsynced rows cannot be deleted.
CREATE TRIGGER trg_change_log_no_edit BEFORE UPDATE ON change_log
WHEN NEW.table_name IS NOT OLD.table_name OR NEW.row_id IS NOT OLD.row_id
  OR NEW.operation IS NOT OLD.operation OR NEW.payload IS NOT OLD.payload
  OR NEW.created_at IS NOT OLD.created_at
BEGIN
    SELECT RAISE(ABORT, 'change_log is append-only: only synced_at may change');
END;

CREATE TRIGGER trg_change_log_no_delete_unsynced BEFORE DELETE ON change_log
WHEN OLD.synced_at IS NULL
BEGIN
    SELECT RAISE(ABORT, 'change_log: cannot delete rows that are not synced yet');
END;

CREATE TRIGGER trg_backup_log_no_update BEFORE UPDATE ON backup_log
BEGIN
    SELECT RAISE(ABORT, 'backup_log is append-only');
END;

-- ---------- append-only and no-hard-delete protection ----------
CREATE TRIGGER trg_stock_movements_no_update BEFORE UPDATE ON stock_movements
BEGIN SELECT RAISE(ABORT, 'stock_movements is append-only: add a reversing row instead'); END;
CREATE TRIGGER trg_stock_movements_no_delete BEFORE DELETE ON stock_movements
BEGIN SELECT RAISE(ABORT, 'stock_movements is append-only: add a reversing row instead'); END;
CREATE TRIGGER trg_ledger_entries_no_update BEFORE UPDATE ON ledger_entries
BEGIN SELECT RAISE(ABORT, 'ledger_entries is append-only: add a reversing row instead'); END;
CREATE TRIGGER trg_ledger_entries_no_delete BEFORE DELETE ON ledger_entries
BEGIN SELECT RAISE(ABORT, 'ledger_entries is append-only: add a reversing row instead'); END;
CREATE TRIGGER trg_payments_no_update BEFORE UPDATE ON payments
BEGIN SELECT RAISE(ABORT, 'payments is append-only: add a reversing row instead'); END;
CREATE TRIGGER trg_payments_no_delete BEFORE DELETE ON payments
BEGIN SELECT RAISE(ABORT, 'payments is append-only: add a reversing row instead'); END;
CREATE TRIGGER trg_audit_log_no_update BEFORE UPDATE ON audit_log
BEGIN SELECT RAISE(ABORT, 'audit_log is append-only: add a reversing row instead'); END;
CREATE TRIGGER trg_audit_log_no_delete BEFORE DELETE ON audit_log
BEGIN SELECT RAISE(ABORT, 'audit_log is append-only: add a reversing row instead'); END;
CREATE TRIGGER trg_purchase_items_no_update BEFORE UPDATE ON purchase_items
BEGIN SELECT RAISE(ABORT, 'purchase_items is append-only: add a reversing row instead'); END;
CREATE TRIGGER trg_purchase_items_no_delete BEFORE DELETE ON purchase_items
BEGIN SELECT RAISE(ABORT, 'purchase_items is append-only: add a reversing row instead'); END;
CREATE TRIGGER trg_purchase_return_items_no_update BEFORE UPDATE ON purchase_return_items
BEGIN SELECT RAISE(ABORT, 'purchase_return_items is append-only: add a reversing row instead'); END;
CREATE TRIGGER trg_purchase_return_items_no_delete BEFORE DELETE ON purchase_return_items
BEGIN SELECT RAISE(ABORT, 'purchase_return_items is append-only: add a reversing row instead'); END;
CREATE TRIGGER trg_invoice_items_no_update BEFORE UPDATE ON invoice_items
BEGIN SELECT RAISE(ABORT, 'invoice_items is append-only: add a reversing row instead'); END;
CREATE TRIGGER trg_invoice_items_no_delete BEFORE DELETE ON invoice_items
BEGIN SELECT RAISE(ABORT, 'invoice_items is append-only: add a reversing row instead'); END;
CREATE TRIGGER trg_sales_return_items_no_update BEFORE UPDATE ON sales_return_items
BEGIN SELECT RAISE(ABORT, 'sales_return_items is append-only: add a reversing row instead'); END;
CREATE TRIGGER trg_sales_return_items_no_delete BEFORE DELETE ON sales_return_items
BEGIN SELECT RAISE(ABORT, 'sales_return_items is append-only: add a reversing row instead'); END;
CREATE TRIGGER trg_users_no_delete BEFORE DELETE ON users
BEGIN SELECT RAISE(ABORT, 'users: hard delete not allowed, set deleted_at instead'); END;
CREATE TRIGGER trg_categories_no_delete BEFORE DELETE ON categories
BEGIN SELECT RAISE(ABORT, 'categories: hard delete not allowed, set deleted_at instead'); END;
CREATE TRIGGER trg_brands_no_delete BEFORE DELETE ON brands
BEGIN SELECT RAISE(ABORT, 'brands: hard delete not allowed, set deleted_at instead'); END;
CREATE TRIGGER trg_suppliers_no_delete BEFORE DELETE ON suppliers
BEGIN SELECT RAISE(ABORT, 'suppliers: hard delete not allowed, set deleted_at instead'); END;
CREATE TRIGGER trg_customers_no_delete BEFORE DELETE ON customers
BEGIN SELECT RAISE(ABORT, 'customers: hard delete not allowed, set deleted_at instead'); END;
CREATE TRIGGER trg_products_no_delete BEFORE DELETE ON products
BEGIN SELECT RAISE(ABORT, 'products: hard delete not allowed, set deleted_at instead'); END;
CREATE TRIGGER trg_batches_no_delete BEFORE DELETE ON batches
BEGIN SELECT RAISE(ABORT, 'batches: hard delete not allowed, set deleted_at instead'); END;
CREATE TRIGGER trg_purchases_no_delete BEFORE DELETE ON purchases
BEGIN SELECT RAISE(ABORT, 'purchases: hard delete not allowed, set deleted_at instead'); END;
CREATE TRIGGER trg_purchase_returns_no_delete BEFORE DELETE ON purchase_returns
BEGIN SELECT RAISE(ABORT, 'purchase_returns: hard delete not allowed, set deleted_at instead'); END;
CREATE TRIGGER trg_invoices_no_delete BEFORE DELETE ON invoices
BEGIN SELECT RAISE(ABORT, 'invoices: hard delete not allowed, set deleted_at instead'); END;
CREATE TRIGGER trg_sales_returns_no_delete BEFORE DELETE ON sales_returns
BEGIN SELECT RAISE(ABORT, 'sales_returns: hard delete not allowed, set deleted_at instead'); END;
CREATE TRIGGER trg_expenses_no_delete BEFORE DELETE ON expenses
BEGIN SELECT RAISE(ABORT, 'expenses: hard delete not allowed, set deleted_at instead'); END;
CREATE TRIGGER trg_settings_no_delete BEFORE DELETE ON settings
BEGIN SELECT RAISE(ABORT, 'settings: hard delete not allowed, set deleted_at instead'); END;

-- ---------- change log for later cloud sync ----------
-- The update trigger also bumps version and updated_at. Never set those in the app.
CREATE TRIGGER trg_stock_movements_cl_ins AFTER INSERT ON stock_movements
BEGIN
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'stock_movements', NEW.id, 'insert');
END;
CREATE TRIGGER trg_ledger_entries_cl_ins AFTER INSERT ON ledger_entries
BEGIN
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'ledger_entries', NEW.id, 'insert');
END;
CREATE TRIGGER trg_payments_cl_ins AFTER INSERT ON payments
BEGIN
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'payments', NEW.id, 'insert');
END;
CREATE TRIGGER trg_purchase_items_cl_ins AFTER INSERT ON purchase_items
BEGIN
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'purchase_items', NEW.id, 'insert');
END;
CREATE TRIGGER trg_purchase_return_items_cl_ins AFTER INSERT ON purchase_return_items
BEGIN
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'purchase_return_items', NEW.id, 'insert');
END;
CREATE TRIGGER trg_invoice_items_cl_ins AFTER INSERT ON invoice_items
BEGIN
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'invoice_items', NEW.id, 'insert');
END;
CREATE TRIGGER trg_sales_return_items_cl_ins AFTER INSERT ON sales_return_items
BEGIN
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'sales_return_items', NEW.id, 'insert');
END;
CREATE TRIGGER trg_users_cl_ins AFTER INSERT ON users
BEGIN
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'users', NEW.id, 'insert');
END;
CREATE TRIGGER trg_categories_cl_ins AFTER INSERT ON categories
BEGIN
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'categories', NEW.id, 'insert');
END;
CREATE TRIGGER trg_brands_cl_ins AFTER INSERT ON brands
BEGIN
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'brands', NEW.id, 'insert');
END;
CREATE TRIGGER trg_suppliers_cl_ins AFTER INSERT ON suppliers
BEGIN
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'suppliers', NEW.id, 'insert');
END;
CREATE TRIGGER trg_customers_cl_ins AFTER INSERT ON customers
BEGIN
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'customers', NEW.id, 'insert');
END;
CREATE TRIGGER trg_products_cl_ins AFTER INSERT ON products
BEGIN
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'products', NEW.id, 'insert');
END;
CREATE TRIGGER trg_batches_cl_ins AFTER INSERT ON batches
BEGIN
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'batches', NEW.id, 'insert');
END;
CREATE TRIGGER trg_purchases_cl_ins AFTER INSERT ON purchases
BEGIN
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'purchases', NEW.id, 'insert');
END;
CREATE TRIGGER trg_purchase_returns_cl_ins AFTER INSERT ON purchase_returns
BEGIN
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'purchase_returns', NEW.id, 'insert');
END;
CREATE TRIGGER trg_invoices_cl_ins AFTER INSERT ON invoices
BEGIN
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'invoices', NEW.id, 'insert');
END;
CREATE TRIGGER trg_sales_returns_cl_ins AFTER INSERT ON sales_returns
BEGIN
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'sales_returns', NEW.id, 'insert');
END;
CREATE TRIGGER trg_expenses_cl_ins AFTER INSERT ON expenses
BEGIN
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'expenses', NEW.id, 'insert');
END;
CREATE TRIGGER trg_settings_cl_ins AFTER INSERT ON settings
BEGIN
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'settings', NEW.id, 'insert');
END;
CREATE TRIGGER trg_users_cl_upd AFTER UPDATE ON users
WHEN NEW.version = OLD.version
BEGIN
    UPDATE users SET version = OLD.version + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'users', NEW.id, 'update');
END;
CREATE TRIGGER trg_categories_cl_upd AFTER UPDATE ON categories
WHEN NEW.version = OLD.version
BEGIN
    UPDATE categories SET version = OLD.version + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'categories', NEW.id, 'update');
END;
CREATE TRIGGER trg_brands_cl_upd AFTER UPDATE ON brands
WHEN NEW.version = OLD.version
BEGIN
    UPDATE brands SET version = OLD.version + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'brands', NEW.id, 'update');
END;
CREATE TRIGGER trg_suppliers_cl_upd AFTER UPDATE ON suppliers
WHEN NEW.version = OLD.version
BEGIN
    UPDATE suppliers SET version = OLD.version + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'suppliers', NEW.id, 'update');
END;
CREATE TRIGGER trg_customers_cl_upd AFTER UPDATE ON customers
WHEN NEW.version = OLD.version
BEGIN
    UPDATE customers SET version = OLD.version + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'customers', NEW.id, 'update');
END;
CREATE TRIGGER trg_products_cl_upd AFTER UPDATE ON products
WHEN NEW.version = OLD.version
BEGIN
    UPDATE products SET version = OLD.version + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'products', NEW.id, 'update');
END;
CREATE TRIGGER trg_batches_cl_upd AFTER UPDATE ON batches
WHEN NEW.version = OLD.version
BEGIN
    UPDATE batches SET version = OLD.version + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'batches', NEW.id, 'update');
END;
CREATE TRIGGER trg_purchases_cl_upd AFTER UPDATE ON purchases
WHEN NEW.version = OLD.version
BEGIN
    UPDATE purchases SET version = OLD.version + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'purchases', NEW.id, 'update');
END;
CREATE TRIGGER trg_purchase_returns_cl_upd AFTER UPDATE ON purchase_returns
WHEN NEW.version = OLD.version
BEGIN
    UPDATE purchase_returns SET version = OLD.version + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'purchase_returns', NEW.id, 'update');
END;
CREATE TRIGGER trg_invoices_cl_upd AFTER UPDATE ON invoices
WHEN NEW.version = OLD.version
BEGIN
    UPDATE invoices SET version = OLD.version + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'invoices', NEW.id, 'update');
END;
CREATE TRIGGER trg_sales_returns_cl_upd AFTER UPDATE ON sales_returns
WHEN NEW.version = OLD.version
BEGIN
    UPDATE sales_returns SET version = OLD.version + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'sales_returns', NEW.id, 'update');
END;
CREATE TRIGGER trg_expenses_cl_upd AFTER UPDATE ON expenses
WHEN NEW.version = OLD.version
BEGIN
    UPDATE expenses SET version = OLD.version + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'expenses', NEW.id, 'update');
END;
CREATE TRIGGER trg_settings_cl_upd AFTER UPDATE ON settings
WHEN NEW.version = OLD.version
BEGIN
    UPDATE settings SET version = OLD.version + 1, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = NEW.id;
    INSERT INTO change_log (id, table_name, row_id, operation) VALUES (lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6))), 'settings', NEW.id, 'update');
END;

-- ---------- views ----------

CREATE VIEW v_batch_stock AS
SELECT b.id AS batch_id, b.product_id, b.batch_no, b.expiry_date,
       COALESCE(SUM(m.qty_delta), 0) AS stock
FROM batches b
LEFT JOIN stock_movements m ON m.batch_id = b.id
WHERE b.deleted_at IS NULL
GROUP BY b.id;

CREATE VIEW v_product_stock AS
SELECT p.id AS product_id, p.name_en, p.name_ur, p.min_stock, p.is_active,
       COALESCE(SUM(s.stock), 0) AS stock_total,
       COALESCE(SUM(CASE WHEN s.expiry_date >= date('now') THEN s.stock ELSE 0 END), 0) AS stock_sellable
FROM products p
LEFT JOIN v_batch_stock s ON s.product_id = p.id
WHERE p.deleted_at IS NULL
GROUP BY p.id;

CREATE VIEW v_low_stock AS
SELECT * FROM v_product_stock WHERE is_active = 1 AND stock_sellable <= min_stock;

CREATE VIEW v_near_expiry AS
SELECT s.batch_id, s.product_id, s.batch_no, s.expiry_date, s.stock,
       CAST(julianday(s.expiry_date) - julianday(date('now')) AS INTEGER) AS days_left
FROM v_batch_stock s
WHERE s.stock > 0
  AND s.expiry_date >= date('now')
  AND s.expiry_date <= date('now', '+' || COALESCE(
        (SELECT CAST(value AS INTEGER) FROM settings WHERE "key" = 'near_expiry_days' AND deleted_at IS NULL), 30) || ' days');

CREATE VIEW v_expired_stock AS
SELECT * FROM v_batch_stock WHERE stock > 0 AND expiry_date < date('now');

CREATE VIEW v_customer_balance AS
SELECT c.id AS customer_id, c.name_en, c.name_ur, c.phone, c.credit_limit,
       COALESCE(SUM(l.amount_delta), 0) AS balance
FROM customers c
LEFT JOIN ledger_entries l ON l.party_type = 'customer' AND l.party_id = c.id
WHERE c.deleted_at IS NULL
GROUP BY c.id;

CREATE VIEW v_supplier_balance AS
SELECT s.id AS supplier_id, s.name_en, s.name_ur, s.phone,
       COALESCE(SUM(l.amount_delta), 0) AS balance
FROM suppliers s
LEFT JOIN ledger_entries l ON l.party_type = 'supplier' AND l.party_id = s.id
WHERE s.deleted_at IS NULL
GROUP BY s.id;

CREATE VIEW v_invoice_item_returnable AS
SELECT ii.id AS invoice_item_id, ii.invoice_id, ii.qty AS qty_sold,
       COALESCE((SELECT SUM(qty) FROM sales_return_items WHERE invoice_item_id = ii.id), 0) AS qty_returned,
       ii.qty - COALESCE((SELECT SUM(qty) FROM sales_return_items WHERE invoice_item_id = ii.id), 0) AS qty_returnable
FROM invoice_items ii;

CREATE VIEW v_invoice_mismatch AS
SELECT i.id AS invoice_id, i.invoice_no, i.total, COALESCE(SUM(ii.line_total), 0) AS lines_total
FROM invoices i
LEFT JOIN invoice_items ii ON ii.invoice_id = i.id
GROUP BY i.id
HAVING i.total <> COALESCE(SUM(ii.line_total), 0);

CREATE VIEW v_profit_by_day AS
SELECT day,
       CAST(SUM(revenue) AS INTEGER) AS revenue,
       CAST(SUM(cost) AS INTEGER) AS cost,
       CAST(SUM(revenue) - SUM(cost) AS INTEGER) AS profit
FROM (
    SELECT date(i.invoice_date) AS day,
           ii.line_total - ii.tax_amount AS revenue,
           CAST(ROUND(ii.cost_price * ii.qty * 1.0 / p.pack_size) AS INTEGER) AS cost
    FROM invoice_items ii
    JOIN invoices i ON i.id = ii.invoice_id
    JOIN products p ON p.id = ii.product_id
    WHERE i.status = 'active'
    UNION ALL
    SELECT date(r.return_date),
           -CAST(ROUND(sri.refund_amount * 1.0 * (ii.line_total - ii.tax_amount) / NULLIF(ii.line_total, 0)) AS INTEGER),
           -CASE WHEN sri.condition = 'resellable'
                 THEN CAST(ROUND(ii.cost_price * sri.qty * 1.0 / p.pack_size) AS INTEGER) ELSE 0 END
    FROM sales_return_items sri
    JOIN sales_returns r ON r.id = sri.sales_return_id
    JOIN invoice_items ii ON ii.id = sri.invoice_item_id
    JOIN invoices i ON i.id = r.invoice_id
    JOIN products p ON p.id = ii.product_id
    WHERE i.status = 'active'
)
GROUP BY day;

INSERT INTO schema_version (version, description) VALUES (1, 'initial schema');
