# Generated by Django 5.2.17 on 2026-09-27 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhataCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('charge_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='customers.customer')),
            ],
            options={
                'ordering': ['-charge_date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='khata_charge_amount_gt_0')],
            },
        ),
        migrations.CreateModel(
            name='KhataPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('EASYPAISA', 'Easypaisa'), ('JAZZCASH', 'JazzCash')], default='CASH', max_length=20)),
                ('paid_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer')),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='khata_payment_amount_gt_0')],
            },
        ),
    ]
