# Generated by Django 5.2.17 on 2026-10-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khatapayment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('EASYPAISA', 'Easypaisa'), ('ADJUSTMENT', 'Return Credit'), ('JAZZCASH', 'JazzCash')], default='CASH', max_length=20),
        ),
    ]
